-------- VERIFICAR ESTRUTURA DA COLUNA PC_TAXA_JUROS -------
USE [SimulaEmprestimo];
GO

SELECT 
    COLUMN_NAME,
    DATA_TYPE,
    NUMERIC_PRECISION,
    NUMERIC_SCALE,
    IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'PRODUTO' AND COLUMN_NAME = 'PC_TAXA_JUROS';

------------- ALTERAR ESTRUTURA DA COLUNA PC_TAXA_JUROS -------------
USE [SimulaEmprestimo];
GO

-- Primeiro apagar os registros existentes
DELETE FROM dbo.PRODUTO;
GO

-- Alterar a coluna para armazenar mais casas decimais
ALTER TABLE dbo.PRODUTO 
ALTER COLUMN PC_TAXA_JUROS DECIMAL(10,8);
GO

-- Agora inserir com as taxas corretas
SET IDENTITY_INSERT dbo.PRODUTO ON;

INSERT INTO dbo.PRODUTO (CO_PRODUTO, NO_PRODUTO, PC_TAXA_JUROS, NU_MINIMO_MESES, NU_MAXIMO_MESES, VR_MINIMO, VR_MAXIMO) 
VALUES 
(1, 'Produto 1', 0.017900000, 0, 24, 200.00, 10000.00),
(2, 'Produto 2', 0.017500000, 25, 48, 10001.00, 100000.00),
(3, 'Produto 3', 0.018200000, 49, 96, 100000.01, 1000000.00),
(4, 'Produto 4', 0.015100000, 96, NULL, 1000000.01, NULL);

SET IDENTITY_INSERT dbo.PRODUTO OFF;
GO

-- Verificar os dados
SELECT 
    CO_PRODUTO,
    NO_PRODUTO,
    PC_TAXA_JUROS,
    CAST(PC_TAXA_JUROS AS DECIMAL(10,8)) AS TAXA_FORMATADA,
    FORMAT(PC_TAXA_JUROS, '0.00000000') AS TAXA_STRING,
    NU_MINIMO_MESES,
    NU_MAXIMO_MESES,
    VR_MINIMO,
    VR_MAXIMO
FROM dbo.PRODUTO
ORDER BY CO_PRODUTO;


