CREATE TABLE dbo.SIMULACAO (
    ID_SIMULACAO BIGINT IDENTITY(1,1) PRIMARY KEY,
    CO_PRODUTO INT NOT NULL,
    VALOR_DESEJADO DECIMAL(18,2) NOT NULL,
    PRAZO INT NOT NULL,
    PC_TAXA_JUROS DECIMAL(10,9) NOT NULL,
    DATA_SIMULACAO DATETIME NOT NULL DEFAULT GETDATE(),
    CONSTRAINT FK_SIMULACAO_PRODUTO FOREIGN KEY (CO_PRODUTO) REFERENCES dbo.PRODUTO(CO_PRODUTO)
);

CREATE TABLE dbo.SIMULACAO_PARCELA (
    ID_PARCELA BIGINT IDENTITY(1,1) PRIMARY KEY,
    ID_SIMULACAO BIGINT NOT NULL,
    TIPO_AMORTIZACAO VARCHAR(10) NOT NULL, -- SAC ou PRICE
    NUMERO INT NOT NULL,
    VALOR_AMORTIZACAO DECIMAL(18,2) NOT NULL,
    VALOR_JUROS DECIMAL(18,2) NOT NULL,
    VALOR_PRESTACAO DECIMAL(18,2) NOT NULL,
    CONSTRAINT FK_PARCELA_SIMULACAO FOREIGN KEY (ID_SIMULACAO) REFERENCES dbo.SIMULACAO(ID_SIMULACAO)
);
