// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimulacaoEmprestimoApi.Data;

#nullable disable

namespace SimulacaoEmprestimoApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SimulacaoEmprestimoApi.Models.Produto", b =>
                {
                    b.Property<int>("CO_PRODUTO")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CO_PRODUTO"));

                    b.Property<string>("NO_PRODUTO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short?>("NU_MAXIMO_MESES")
                        .HasColumnType("smallint");

                    b.Property<short>("NU_MINIMO_MESES")
                        .HasColumnType("smallint");

                    b.Property<decimal>("PC_TAXA_JUROS")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("VR_MAXIMO")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("VR_MINIMO")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CO_PRODUTO");

                    b.ToTable("PRODUTO", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
